ekf_filter_node:
  ros__parameters:
    frequency: 100.0  # Output frequency (Hz)
    sensor_timeout: 0.1
    two_d_mode: true  # Set to false for 3D
    predict_to_current_time: true

    map_frame: map
    odom_frame: odom
    world_frame: odom
    base_link_frame: base_link
    publish_tf: true

    odom0: /utlidar/robot_odom  # High-frequency odometry topic
    odom0_config: [true, true, false,  # x, y, z
                  false, false, true,  # roll, pitch, yaw
                  true, true, false,   # vx, vy, vz
                  false, false, true,  # vroll, vpitch, vyaw
                  false, false, false] # ax, ay, az
    odom0_differential: false
    odom0_relative: false

    odom1: /odom_lidar
    odom1_config: [true, true, false,  # x, y, z
                  false, false, true,  # roll, pitch, yaw
                  false, false, false, # vx, vy, vz
                  false, false, false, # vroll, vpitch, vyaw
                  false, false, false] # ax, ay, az
    odom1_differential: false
    odom1_relative: false